export enum ApiStatusCodeConst {
  SUCCESS = "SUCCESS",
  BAD_REQUEST = "BAD_REQUEST",
  SERVER_ERROR = "SERVER_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  UN_AUTHORIZED = "UN_AUTHORIZED",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
}
